### ISSUE TITLE
An error was thrown when using the Azure static web app for automatic deployment.

### ISSUE THREAD

**Issue by satellitex** [Azure/static-web-apps#143]
https://github.com/staketechnologies/lockdrop-ui/runs/1055466320?check_suite_focus=true
```
Running 'yarn install --prefer-offline --production'...

yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-plugin-react-hooks@0.0.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /github/workspace/.oryx_prod_node_modules/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /github/workspace/.oryx_prod_node_modules/node_modules/node-hid
Output:
prebuild-install WARN install libusb-1.0.so.0: cannot open shared object file: No such file or directory
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.3 | linux | x64
gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/tmp/oryx/platforms/nodejs/12.18.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/github/workspace/.oryx_prod_node_modules/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/oryx/platforms/nodejs/12.18.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/github/home/.cache/node-gyp/12.18.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/github/home/.cache/node-gyp/12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/oryx/platforms/nodejs/12.18.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/github/home/.cache/node-gyp/12.18.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/github/workspace/.oryx_prod_node_modules/node_modules/node-hid',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/tmp/oryx/platforms/nodejs/12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-1035-azure
gyp ERR! command "/tmp/oryx/platforms/nodejs/12.18.3/bin/node" "/tmp/oryx/platforms/nodejs/12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /github/workspace/.oryx_prod_node_modules/node_modules/node-hid
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok


---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a Github issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

**Comment by miwebst** [comment]
Looks like it is looking for the libusb library and not finding it. Can you try following the guidance in this issue and seeing if adding that library unblocks your deployment?

https://github.com/Azure/static-web-apps/issues/99

**Comment by simonaco** [comment]
@satellitex please reopen the issue if you're still seeing the initial errors.
