### ISSUE TITLE
blazor + static web app = some error after publish

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#320]
A few days ago started giving this error, I don't remember exactly which one, but it never disappeared
![image](https://user-images.githubusercontent.com/12803050/110970883-f4004e00-8338-11eb-9cfb-0a719d30ffcd.png)

And today, right after a publication, this one started to appear:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Function host is not running.
VerusDate.Shared.Helper.NotificationException: Function host is not running.
   at VerusDate.Web.Core.ApiCore.<ReturnResponse>d__0`1[[VerusDate.Shared.Model.ProfileModel, VerusDate.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at VerusDate.Web.Core.ApiCore.<Get>d__2`1[[VerusDate.Shared.Model.ProfileModel, VerusDate.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at VerusDate.Web.Api.ProfileApi.Profile_Get(HttpClient http, ISyncSessionStorageService storage)
   at VerusDate.Web.Shared.HeadLayout.LoadData()
   at VerusDate.Web.Shared.HeadLayout.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by anthonychu** [comment]
Looks like the Blazor app is fine, the problem is your front end is calling a function and the function app is down.

Here's one error I can see: `System.ArgumentNullException : Value cannot be null. (Parameter 'containerId')` Did you change anything related to your function app or your app settings since the last successful deployment?

If your app settings names have `:` in it, try changing them to double underscore `__` instead.

**Comment by drma-dev** [comment]
In fact, I had made changes to that recently. but where do i see this error? not yet in service?

what about the service worker error?

**Comment by drma-dev** [comment]
and about the character `:` I have several like this and they all work normally

**Comment by drma-dev** [comment]
@anthonychu
