### ISSUE TITLE
Error: Tried to overwrite /working_dir/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

### ISSUE THREAD

**Issue by CCorio** [Azure/static-web-apps#387]
Hello - I am having a build error for an Angular 11 app running on Node.js.  I am using Azure DevOps to host the application and its pipeline to publish to my Azure Static Web App.  Is there an obvious issue to fix or should I provide additional information?

Everything builds and runs fine locally... 

Thanks!

> test-app@0.0.0 build /working_dir
> ng build

Compiling @angular/core : es2015 as esm2015

An error occurred during the build:
Error: Tried to overwrite /working_dir/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:58:27)
    at NewEntryPointFileWriter.writeFile (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:128:53)
    at /working_dir/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:47:30)
    at writeBundle (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:58:36)
    at /working_dir/node_modules/@angular/compiler-cli/ngcc/src/execution/create_compile_function.js:65:25
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:36:17)
    at /working_dir/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/working_dir/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/working_dir/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/working_dir/node_modules/@ngtools/webpack/src/ngcc_processor.js:163:16)
    at /working_dir/node_modules/@ngtools/webpack/src/ivy/host.js:109:18
    at /working_dir/node_modules/@ngtools/webpack/src/ivy/host.js:39:24
An unhandled exception occurred: Tried to overwrite /working_dir/node_modules/@angular/core/core.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
See "/tmp/ng-83DRSy/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! test-app@0.0.0 build: `ng build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the test-app@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-27T17_43_50_820Z-debug.log

**Comment by CCorio** [comment]
I was able to get this to reproduce with the standard Angular new application so I figured that's a better place to start.
