### ISSUE TITLE
ManagedIdentity does not work for C# Managed API

### ISSUE THREAD

**Issue by lenisha** [Azure/static-web-apps#466]
**Describe the bug**
Trying to get Managed Identity Token in Managed C# API using `Azure.Identity1 package.

- System Managed Identity enabled on SWA
- Code in Function API 
```
 // add Identity Token
  DefaultAzureCredential credential = new DefaultAzureCredential();
  var accessToken = credential.GetToken(new TokenRequestContext(new[] { "https://storage.azure.com" })).Token;

```

Failure **- ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.**

```
icrosoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: deepzoom
 ---> Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials.
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
- ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
- Visual Studio Token provider can't be accessed at .IdentityService\AzureServiceAuth\tokenprovider.json
- Stored credentials not found. Need to authenticate user in VSCode Azure Account.
- Azure CLI not installed
- PowerShell is not installed.
 ---> System.AggregateException: Multiple exceptions were encountered while attempting to authenticate. (EnvironmentCredential authentication unavailable. Environment variables are not fully configured.) (ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.) (Visual Studio Token provider can't be accessed at .IdentityService\AzureServiceAuth\tokenprovider.json) (Stored credentials not found. Need to authenticate user in VSCode Azure Account.) (Azure CLI not installed) (PowerShell is not installed.)
 ---> Azure.Identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.EnvironmentCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.EnvironmentCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)

```

**Comment by anthonychu** [comment]
Managed identity is currently unavailable in the function apps provided by Static Web Apps. Please use the [bring your own function apps](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own) feature (enable and use the managed identity in the function app).

**Comment by miwebst** [comment]
This is described as only for bring your own function apps here: https://docs.microsoft.com/en-us/azure/static-web-apps/apis

**Comment by KushagraAgrawal-TomTom** [comment]
Is Managed Identity still not available in the function apps provided by Static web apps @anthonychu 
I'm getting a different error -
`ManagedIdentityCredential.get_token_info failed: App Service managed identity configuration not found in environment. invalid_scope`
