### ISSUE TITLE
API functions all returning 503 service unavailable (Function host is not running).

### ISSUE THREAD

**Issue by epieters** [Azure/static-web-apps#652]
**Describe the bug**
API functions all returning 503 service unavailable (Function host is not running).

Error returned:
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering Component: net_http_message_not_success_statuscode, 503, Service Unavailable 
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 503, Service Unavailable
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[System.Collections.Generic.List`1[[BlazorApp.Client.Pages.ResultsIcoCheck.IcoCheck, Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BlazorApp.Client.Pages.ResultsIcoCheck.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

I'm using the Standard Github actions workflow 
staticwebapp.config.json
{
  "routes": [
    {
      "route": "/login",
      "redirect": "/.auth/login/aad?post_login_redirect_uri=/results-ico-check"
    },
    {
      "route": "/",
      "redirect": "/results-ico-check"
    },
    {
      "route": "/logout",
      "redirect": "/.auth/logout?post_logout_redirect_uri=/"
    },
    {
      "route": "/api/*",
      "methods": [ "GET" ],
      "allowedRoles": [ "reader" ]
    },
    {
      "route": "/api/UploadFunction",
      "methods": [ "POST" ],
      "allowedRoles": [ "reader" ]
    }

  ],
  "navigationFallback": {
    "rewrite": "/index.html"
  },
  "responseOverrides": {
    "401": {
      "redirect": "/login",
      "statusCode": 302
    }
  }
}

**Expected behavior**
This was working for me before, but stop working for no clear reason (well at least not for me).
I can run the SWA + Functions on my local environment

Not clear where to look for additional debug information or errorlog.

**Comment by epieters** [comment]
Not sure why but upgrade to .NET6 & Functions 4 solved my issue.
