### ISSUE TITLE
Build and deploy problem with Static web service with Vue

### ISSUE THREAD

**Issue by Vampiredk** [Azure/static-web-apps#754]
i have been having some troubles with making a static web service with Vue, i am getting this error message that i can´t really find a solution to

```
 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /github/workspace/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /github/workspace/node_modules/webpack/lib/webpack.js:148:8
    at /github/workspace/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/github/workspace/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/github/workspace/node_modules/webpack/lib/Cache.js:150:23)
    at /github/workspace/node_modules/webpack/lib/Compiler.js:1212:15
    at Hook.eval [as callAsync] (eval at create (/github/workspace/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
```

there is also this one but i says it´s optional so not sure if it´s importent

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by farshidrezaei** [comment]
same issue
